name: Build and Publish Template Output to Main

on:
  push:
    branches: ["develop", "making-it-work"]

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Make the script executable and run it
      - name: Make the script executable
        run: |
             chmod +x ./run_the_template.bash
             ./run_the_template.bash

      # Step 3: Initialize a new Git repository in BugReport and push to main
      - name: Initialize a new Git repository in BugReport
        run: |
          cd BlazoriseBugReport
          git init
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m "Publish template output to main"
          git branch -M main
        
      # Step 4: Force push BugReport as a new orphaned main branch
      - name: Push to main branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd BlazoriseBugReport
          git remote add origin https://github.com/${{ github.repository }}.git
          git push -f origin main
